name: Lint and package

on:
  pull_request:
  push:
    paths-ignore:
      - '**.asc'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 28.1
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test
        run: make test

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 28.1
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Package
        run: make package
        
